### ISSUE TITLE
Research and document puzzles

### ISSUE THREAD

**Issue by Evionis** [CSI-280/python-game#1]
Research and document some basic puzzle ideas that can realistically be implemented in a text-based game and explain how that might work. Could be a collaborative issue between several people if they are interested.

**Comment by kaiwilens** [comment]
Should we put the links and the ideas into the shared google doc?

**Comment by Evionis** [comment]
That's what I was thinking, and then put the link into the readme

**Comment by Evionis** [comment]
https://docs.google.com/document/d/1RTI1KXnnTR8Qo6oZBsA5HZLdGG-oU7rfZ9q67ya60f4/edit?usp=sharing
