### ISSUE TITLE
Set up project files

### ISSUE THREAD

**Issue by Michael12309** [CSI-280/python-game#14]
What I mean by this is to set up classes/objects for our game.  Are we going to have a module (file) that handles rooms?  A module for the player/enemies?  How is everything going to interact with the main game loop?  Ideally, we would have our game loop/engine.py file be as simple as possible and objects/classes/modules that handle all aspects of our game separately.

Creating all the files we need is what this issue is really for.  You don't have to write much code in them, just a rough layout is what we need.  It doesn't have to be perfect and can be subject to change but it would allow all of us to have something to go off of.

This issue has to be done pretty quickly so the rest of us can start working.

**Comment by kaiwilens** [comment]
Are we thinking of having a player inventory in the game? Just wonderin.

**Comment by Michael12309** [comment]
@kaiwilens I would say yeah but who knows what other people have in mind.
In my mind, we have something similar to rogue (the original game) with semi-random rooms, the same way that the Binding of Isaac works (random rooms picked from a pool of premade rooms).

Maybe I'm not totally informed as to what we're doing though.

**Comment by kaiwilens** [comment]
Ok cool, I do have an old python project/game that used an inventory system which could help us with this project, but we'll see.

**Comment by Michael12309** [comment]
@kaiwilens nice!  The tutorial I was looking at (http://rogueliketutorials.com/tutorials/tcod/) has a section on inventory too: http://rogueliketutorials.com/tutorials/tcod/part-8/

**Comment by wesbeard** [comment]
This should be complete now that we have the player moving and walls blocking movement, now we can work on more specific features and changes.
