### ISSUE TITLE
set up a random room generator

### ISSUE THREAD

**Issue by ghost** [CSI-280/python-game#16]
I think we decided to go half and half on room generation, with half being random, and half being scripted. creating a system for random room generation would be nice, and possibly also getting it to draw to the screen would be even better.

**Comment by kaiwilens** [comment]
Would this be in its own file or in one of the main files?

**Comment by ghost** [comment]
maybe we could have just one file dedicated to room setup. in it we have code for random generation as well as code for rooms that we want scripted

**Comment by Evionis** [comment]
Given the reduced time, I think we should change this issue a bit. I think that before we try to build the random generator we should do an exhaustive analysis of "what is a room". Meaning, we should document the structure of a room, what can be in a room, how you can move into and out of a room, that kind of thing. It will be hard to build the random gen if we have to come up with all that on the fly.

**Comment by wesbeard** [comment]
The way I'm currently thinking this should be done is that we have a pre-set start and end room and then randomly pull from the map list to fill the floors in between. Basically we can have a list of rooms, it can be longer or shorter depending on the difficulty, and each room is an index in the list. This way we could go up or down floors both forward and backwards by increasing or decreasing the index, something that would be a lot harder if we were randomizing as we went along.

**Comment by wesbeard** [comment]
The game now selects a map randomly from the map files folder.
