### ISSUE TITLE
Set up an inventory file

### ISSUE THREAD

**Issue by kaiwilens** [CSI-280/python-game#17]
I was thinking of setting up an inventory system for the game. Like maybe, in the beginning, we'll have the player pick up items (weapons, healing stuff, etc.) in a default room and then it will go into the randomly generated rooms. I'm not exactly sure how the items will be implemented in the randomly generated rooms but I'm guessing we'll figure it out. 

I do have an old python project/game that used an inventory system (you can buy and sell stuff) which could help us with this project. I can share it in the shared google folder.

**Comment by lhvinton** [comment]
For the inventory system are we considering a limited inventory (some predetermined number of slots) or an unlimited inventory where we can fit as much as we want?

**Comment by kaiwilens** [comment]
Tbh I think we should try to use an unlimited inventory first? I'll upload my files to the google folder now.
