### ISSUE TITLE
Maintain Files

### ISSUE THREAD

**Issue by Ethan-Trope** [CSI-280/python-game#24]
As we progress throughout the creation of the game it will be a good idea to make sure each of our files are organized in a manner that is easy to understand. So for this issue you would be sorting through the README file and others and making sure they are in a format that is easily understandable, as it will let us work better as a group. This is not a high priority or difficult issue so it might be ideal to assign yourself to another issue as well as this one if you choose to do so. Additionally, making sure the files are organized should ideally be done every week.

**Comment by ghost** [comment]
will probably do some reorganization tonight after the meeting, need to know everyone's status before i start changing the whole structure of the repo

**Comment by wesbeard** [comment]
This isn't really necessary for the remainder of the project
