### ISSUE TITLE
Make a Room

### ISSUE THREAD

**Issue by JoshBogin** [CSI-280/python-game#27]
Our project will be consisting of a lot of rooms which serve different purposes. Therefore, for this issue I just want someone to work on one of them. Continue to follow the tcod tutorials and figure out how to make a room that is more than just empty (whether a battle with enemy or a puzzle). It does not have to be too complicated but rather a basic room with some new entities or additions.

**Comment by wesbeard** [comment]
Looks like we have figured out how printing walls and did the map part of the tutorial. The map creator should probably fill the role of the drawing maps from now on.
