### ISSUE TITLE
Edit and Format the README File

### ISSUE THREAD

**Issue by JoshBogin** [CSI-280/python-game#3]
For this issue, I would like 1 to 2 people to work on the readme file and figure out how it should be formated. They should work together with other issues that involve brainstorming ideas for the game to get those ideas into the readme file so everything will be properly documented for future issues.

**Comment by wesbeard** [comment]
I've added some basic sections like an about, design guide, ascii character reference, keymap chart, and credits area that we can fill out as we develop further.
