### ISSUE TITLE
Begin to implement maps, items, and other ideas into the basic functions

### ISSUE THREAD

**Issue by JoshBogin** [CSI-280/python-game#37]
This is a very general idea and anybody can take part in it. I just want people to take the basic code that we have been developing from the tcod tutorials and make it our own. We are going to need to put the maps we have created into the actual game by modifying our initial code to except and utilize them. We also need to figure out things like items and how to get them into the game. Overall, we just need to develop the game closer to being a finished project.

**Comment by lhvinton** [comment]
@JoshBogin I just finished working on the generic class for item. Currently they only show up on the map and can be picked up but we still need to add functionality to them and a UI to actually view them.

**Comment by JoshBogin** [comment]
@lhvinton Yeah I saw your issue and it looks good. The item part seems good but we still need to do more in terms of the floors themselves.

**Comment by wesbeard** [comment]
Replaced by more specific issues.
