### ISSUE TITLE
Research creating GUI applications in python

### ISSUE THREAD

**Issue by ghost** [CSI-280/python-game#5]
Python is not typically used for games, and for good reason. It might be best to figure out exactly how we should approach the issue of creating a GUI for the game, or if we just want to do it within the terminal itself. Might need a person or two on this issue.

**Comment by Michael12309** [comment]
My vote is to use [libcod](https://github.com/libtcod/libtcod), it's literally [made](http://roguecentral.org/doryen/libtcod/projects-2/) for stuff like this.

**Comment by steven-pershyn** [comment]
After looking into the suggestion provide, I believe that libtcod is the preferred GUI we should use for our game.
