### ISSUE TITLE
Design our game graphics (in ascii)

### ISSUE THREAD

**Issue by Michael12309** [CSI-280/python-game#6]
(This is a fun issue)

It would be nice to have an idea as to what our game is going to look like.  This can include:
- Will we have floors?  If so:
    - Will we have a randomized dungeon with interconnected rooms?  What will they look like?
    - What will the background, walls, floors look like?  Make sure they contrast well, are clear to the user, etc.
- What will the screen look like at any given time?
- If we have an inventory/menu:
    - What will that look like in ascii?
- Whose our player? Who are the enemies?
- If puzzle elements are included in our game, how are we going to represent these puzzles in ascii?

I'm not sure if we're going to be using [libcod](https://github.com/libtcod/libtcod) but if we are, base your decisions on design from this library.

Since this issue isn't very complex, I'd recommend only one person take it.

Our design for the game will probably change as the project goes on, but I'd like to have a basis that we can build on and change.

To resolve this issue, please provide one or more screenshots or a representation of the design you came up with.

**Comment by wesbeard** [comment]
I've looked into the graphics involved in libtcod and have a better understanding of it now. I think this is something that's going to have to develop as we go along, but I've added a section to the readme where people can keep a key of ascii characters and what they represent.
