### ISSUE TITLE
Make stairs change floors

### ISSUE THREAD

**Issue by wesbeard** [CSI-280/python-game#61]
So far we have the stairs in the game as 'u' and 'd' for up and down but we need them to be intractable and actually go to the previous or level when interacted with. The levels are just stored in a list so it's as easy and incrementing the list index and display that next map, although this probably requires writing a new change map function since right now we only select a map by random.

**Comment by Michael12309** [comment]
I added going up to the next floor but forgot to add going down.  Also, we don't have the list of maps yet.  In my most recent pull request though, you can see multiple floors by pressing G on an "up-stairs."

I'll add the rest tomorrow.

**Comment by Michael12309** [comment]
Ok done
